server:
  port: 8080
#  contextPath: /mvc
#---
#spring:
#  profiles: prod,local,default
#datasource:
#  sampleapp:
#    url: jdbc:mysql://localhost:3306/mvc
#    username: root
#    password:
#    driverClassName: com.mysql.jdbc.Driver
#    defaultSchema:
#    maxPoolSize: 20
#    hibernate:
#      hbm2ddl.method: update
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod,local,default
  datasource:
    url: jdbc:mysql://localhost:3306/mvc
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    defaultSchema:
    maxActive: 10
    maxIdle: 5
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 60000


    # Hikari Properties
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 20
      pool-name: HikariPool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      # show-sql: true

#Set Logging hikari to DEBUG mode
logging:
  level:
    com.zaxxer.hikari: debug
# org.hibernate: off
